export const PatientFormData = {
    firstName: "",
    lastName: "",
    email: "",
    password: "",
    confirmPassword: "",
    phone: "",
    age: "",
    height: "",
    weight: "",
    gender: "",
    bloodGroup: "",
    dob: "",
    country: "",
    state: "",
    city: "",
    address: "",
    role: "patient",
  }