  export const DoctorFormData = {
    name: "",
    qualification: "",
    gender: "",
    speciality: "",
    workOnStart: "",
    workingTimeStart: "",
    checkUpTimeStart: "",
    breakTimeStart: "",
    experience: "",
    phone: "",
    countryCode: "",
    age: "",
    email: "",
    country: "",
    state: "",
    city: "",
    zipCode: "",
    doctorAddress: "",
    description: "",
    onlineConsultationRate: "",
    currentHospital: "",
    hospitalName: "",
    hospitalAddress: "",
    worksiteLink: "",
    emergencyContactNo: "",
    signature: null,
    profilePicture: null,
    password: "",
    confirmPassword: "",
    hospital: "",
  }

  //static
export const countryCodes = [
    { code: "+1", country: "USA" },
    { code: "+91", country: "India" },
    { code: "+44", country: "UK" },
    { code: "+61", country: "Australia" },
    { code: "+49", country: "Germany" },
  ];

export const timeOptions = [
    "08:00",
    "08:30",
    "09:00",
    "09:30",
    "10:00",
    "10:30",
    "11:00",
    "11:30",
    "12:00",
    "12:30",
    "13:00",
    "13:30",
    "14:00",
    "14:30",
    "15:00",
    "15:30",
    "16:00",
    "16:30",
    "17:00",
    "17:30",
    "18:00",
    "18:30",
    "19:00",
    "19:30",
    "20:00",
    "20:30",
    "21:00",
    "21:30",
  ];